addons:
  postgresql: 9.5
language: ruby
gemfile:
  - gemfiles/activerecord_4.gemfile
  - gemfiles/activerecord_5.gemfile
before_install: gem install bundler -v 1.14.5
before_script: createdb -U postgres rein_test
script: bundle exec rake test
